version: '3.8'
services:
  github-app:
    build: ./docker
    volumes:
      - ./:/var/www/html/
  nginx:
    image: nginx 
    ports:
      - 8085:80 
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306