FROM php:8.1-fpm
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN apt-get update \
  # PHP の GD ライブラリ
  && apt-get install -y \
    # zlib1g-dev libpng-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
  && docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg \
    --with-webp \
    --with-xpm \
  && docker-php-ext-install -j$(nproc) gd
RUN apt-get update && apt-get install -y \
    git vim unzip libzip-dev libicu-dev libonig-dev \
&& docker-php-ext-install pdo_mysql intl zip bcmath

RUN mkdir /etc/nginx/
RUN mkdir /etc/nginx/conf.d
RUN touch /etc/nginx/conf.d/default.conf
# Node.jsをインストール
RUN curl -SL https://deb.nodesource.com/setup_15.x | bash
RUN apt-get install -y nodejs